import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadContextHandoffDeliveredPayload as ContractsThreadContextHandoffDeliveredPayloadSchema,
  ThreadContextHandoffDeliveryFailedPayload as ContractsThreadContextHandoffDeliveryFailedPayloadSchema,
  ThreadContextHandoffPreparedPayload as ContractsThreadContextHandoffPreparedPayloadSchema,
  ThreadTeamTaskCloseRequestedPayload as ContractsThreadTeamTaskCloseRequestedPayloadSchema,
  ThreadTeamTaskCreatedPayload as ContractsThreadTeamTaskCreatedPayloadSchema,
  ThreadTeamTaskMessageRequestedPayload as ContractsThreadTeamTaskMessageRequestedPayloadSchema,
  ThreadTeamTaskStartedPayload as ContractsThreadTeamTaskStartedPayloadSchema,
  ThreadTeamTaskStatusChangedPayload as ContractsThreadTeamTaskStatusChangedPayloadSchema,
  ThreadTeamTaskSummaryUpdatedPayload as ContractsThreadTeamTaskSummaryUpdatedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;
export const ThreadContextHandoffPreparedPayload =
  ContractsThreadContextHandoffPreparedPayloadSchema;
export const ThreadContextHandoffDeliveredPayload =
  ContractsThreadContextHandoffDeliveredPayloadSchema;
export const ThreadContextHandoffDeliveryFailedPayload =
  ContractsThreadContextHandoffDeliveryFailedPayloadSchema;
export const ThreadTeamTaskCreatedPayload = ContractsThreadTeamTaskCreatedPayloadSchema;
export const ThreadTeamTaskStartedPayload = ContractsThreadTeamTaskStartedPayloadSchema;
export const ThreadTeamTaskStatusChangedPayload = ContractsThreadTeamTaskStatusChangedPayloadSchema;
export const ThreadTeamTaskSummaryUpdatedPayload =
  ContractsThreadTeamTaskSummaryUpdatedPayloadSchema;
export const ThreadTeamTaskMessageRequestedPayload =
  ContractsThreadTeamTaskMessageRequestedPayloadSchema;
export const ThreadTeamTaskCloseRequestedPayload =
  ContractsThreadTeamTaskCloseRequestedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
