const SOURCE_LIKE_EXTENSIONS = new Set([
  ".js",
  ".jsx",
  ".cjs",
  ".mjs",
  ".ts",
  ".tsx",
  ".cts",
  ".mts",
  ".vue",
  ".svelte",
  ".astro",
  ".py",
  ".pyi",
  ".rb",
  ".go",
  ".rs",
  ".java",
  ".kt",
  ".kts",
  ".c",
  ".h",
  ".cc",
  ".hh",
  ".cpp",
  ".hpp",
  ".cs",
  ".swift",
  ".dart",
  ".ex",
  ".exs",
  ".erl",
  ".hrl",
  ".gleam",
  ".zig",
  ".lua",
  ".r",
  ".jl",
  ".hs",
  ".ml",
  ".mli",
  ".sh",
  ".bash",
  ".zsh",
  ".fish",
  ".ps1",
  ".sql",
  ".graphql",
  ".gql",
  ".proto",
  ".json",
  ".jsonc",
  ".yaml",
  ".yml",
  ".toml",
  ".xml",
  ".hcl",
  ".tf",
  ".css",
  ".scss",
  ".sass",
  ".less",
  ".html",
  ".htm",
]);

const SOURCE_LIKE_BASENAMES = new Set([
  "dockerfile",
  "containerfile",
  "makefile",
  "gnumakefile",
  "justfile",
  "procfile",
  "cmakelists.txt",
  "build",
  "build.bazel",
  "workspace",
  "tiltfile",
  "earthfile",
  "vagrantfile",
  "rakefile",
  "gemfile",
  "podfile",
  "brewfile",
  "fastfile",
  ".editorconfig",
]);

const IGNORED_DIRECTORY_NAMES = new Set([
  ".git",
  ".svn",
  ".hg",
  "node_modules",
  "vendor",
  ".venv",
  "venv",
  "env",
  "site-packages",
  "__pycache__",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  ".tox",
  ".nox",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".astro",
  ".turbo",
  ".cache",
  ".parcel-cache",
  "dist",
  "build",
  "out",
  "target",
  ".gradle",
  "pods",
  "carthage",
  ".build",
  "deriveddata",
  ".dart_tool",
  ".pub-cache",
  "deps",
  "_build",
  ".terraform",
  ".serverless",
  ".aws-sam",
  "coverage",
  "obj",
  "debug",
  "release",
  "__generated__",
  "__snapshots__",
  "__screenshots__",
  ".tanstack",
  "release-mock",
  ".logs",
]);

const IGNORED_BASENAMES = new Set([
  "bun.lock",
  "bun.lockb",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "cargo.lock",
  "composer.lock",
  "pipfile.lock",
  "poetry.lock",
  "agents.md",
  "claude.md",
  "memory.md",
  "skill.md",
]);

const EXCLUDED_SUFFIXES = [
  ".map",
  ".min.js",
  ".min.css",
  ".snap",
  ".blockmap",
  ".ipynb",
  ".generated.ts",
  ".generated.tsx",
  ".generated.js",
  ".generated.jsx",
  ".generated.json",
  ".gen.ts",
  ".gen.tsx",
  ".gen.js",
  ".gen.jsx",
];

const EXCLUDED_MARKDOWN_EXTENSIONS = new Set([".md", ".mdx", ".rst", ".adoc", ".txt"]);

const GENERATED_MARKERS = [
  "@generated",
  "generated by",
  "auto-generated",
  "automatically generated",
  "do not edit",
];

export const AUTHORED_SOURCE_CODE_STATS_BASIS = "authored-source-cross-stack-v1";

function normalizePath(relativePath: string): string {
  return relativePath
    .replaceAll("\\", "/")
    .replace(/^\.\/+/, "")
    .replace(/^\/+/, "");
}

function basename(relativePath: string): string {
  const normalized = normalizePath(relativePath);
  const lastSlash = normalized.lastIndexOf("/");
  return lastSlash === -1 ? normalized : normalized.slice(lastSlash + 1);
}

function extension(relativePath: string): string {
  const name = basename(relativePath);
  const dotIndex = name.indexOf(".");
  return dotIndex === -1 ? "" : name.slice(dotIndex).toLowerCase();
}

export function shouldIgnoreCodeStatsPath(relativePath: string): boolean {
  const normalized = normalizePath(relativePath);
  if (normalized.length === 0) {
    return true;
  }

  const segments = normalized.split("/").filter((segment) => segment.length > 0);
  if (segments.some((segment) => IGNORED_DIRECTORY_NAMES.has(segment.toLowerCase()))) {
    return true;
  }

  const name = basename(normalized);
  const loweredName = name.toLowerCase();
  if (IGNORED_BASENAMES.has(loweredName)) {
    return true;
  }
  if (EXCLUDED_SUFFIXES.some((suffix) => loweredName.endsWith(suffix))) {
    return true;
  }

  const fileExtension = extension(loweredName);
  return EXCLUDED_MARKDOWN_EXTENSIONS.has(fileExtension);
}

export function isSourceLikePath(relativePath: string): boolean {
  const normalized = normalizePath(relativePath);
  if (shouldIgnoreCodeStatsPath(normalized)) {
    return false;
  }

  const loweredName = basename(normalized).toLowerCase();
  if (SOURCE_LIKE_BASENAMES.has(loweredName)) {
    return true;
  }

  const loweredPath = normalized.toLowerCase();
  return [...SOURCE_LIKE_EXTENSIONS].some((candidate) => loweredPath.endsWith(candidate));
}

export function isLikelyGeneratedSource(content: string): boolean {
  const head = content.slice(0, 2048).toLowerCase();
  return GENERATED_MARKERS.some((marker) => head.includes(marker));
}

export function countNonEmptyLines(content: string): number {
  if (content.length === 0) {
    return 0;
  }
  return content
    .split(/\r?\n/)
    .reduce((count, line) => count + (line.trim().length > 0 ? 1 : 0), 0);
}

export function approximateTokenCount(content: string): number {
  try {
    const matches = content.match(/\p{L}[\p{L}\p{M}\p{N}_-]*|\p{N}+|[^\s]/gu);
    return matches?.length ?? 0;
  } catch {
    return Math.ceil(new TextEncoder().encode(content).length / 4);
  }
}
